version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s97vf2kuf97v"
s3_prefix = "firstlambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
